export const COLUMBIA_DEMO_EVENTS = [
  {
    id: '1',
    title: 'Butler Library Study Session',
    startTime: '2:00 PM',
    endTime: '4:00 PM',
    venue: 'Butler Library',
    distance: '0.1 mi',
    category: 'academic',
    isFree: true,
    organizer: 'Columbia College',
  },
  {
    id: '2',
    title: 'Lerner Hall Mixer',
    startTime: '6:00 PM',
    endTime: '8:00 PM',
    venue: 'Lerner Hall',
    distance: '0.2 mi',
    category: 'social',
    isFree: true,
    organizer: 'Student Affairs',
  },
  {
    id: '3',
    title: 'SEAS Career Fair Prep Workshop',
    startTime: '3:00 PM',
    endTime: '5:00 PM',
    venue: 'Mudd Building',
    distance: '0.3 mi',
    category: 'career',
    isFree: true,
    organizer: 'SEAS',
  },
  {
    id: '4',
    title: 'Miller Theatre Concert: Contemporary Ensemble',
    startTime: '7:30 PM',
    endTime: '9:30 PM',
    venue: 'Miller Theatre',
    distance: '0.4 mi',
    category: 'arts',
    isFree: false,
    organizer: 'Miller Theatre',
  },
]

export const COLUMBIA_DEMO_MARKERS = [
  {
    id: '1',
    longitude: -73.9626,
    latitude: 40.8075,
    title: 'Butler Library Event',
    category: 'academic',
    type: 'school' as const,
  },
  {
    id: '2',
    longitude: -73.9635,
    latitude: 40.8080,
    title: 'Lerner Hall Social',
    category: 'social',
    type: 'club' as const,
  },
  {
    id: '3',
    longitude: -73.9615,
    latitude: 40.8070,
    title: 'SEAS Career Fair',
    category: 'career',
    type: 'school' as const,
  },
  {
    id: '4',
    longitude: -73.9640,
    latitude: 40.8065,
    title: 'Miller Theatre Concert',
    category: 'arts',
    type: 'club' as const,
  },
]

