export const NYU_DEMO_EVENTS = [
  {
    id: 'nyu-1',
    title: 'Bobst Library Study Night',
    startTime: '7:00 PM',
    endTime: '10:00 PM',
    venue: 'Bobst Library',
    distance: '0.1 mi',
    category: 'academic',
    isFree: true,
    organizer: 'NYU Student Government',
  },
  {
    id: 'nyu-2',
    title: 'Kimmel Game Night',
    startTime: '8:00 PM',
    endTime: '11:00 PM',
    venue: 'Kimmel Center for University Life',
    distance: '0.2 mi',
    category: 'social',
    isFree: true,
    organizer: 'Kimmel Activities',
  },
  {
    id: 'nyu-3',
    title: 'Stern Career Workshop',
    startTime: '4:00 PM',
    endTime: '6:00 PM',
    venue: 'Stern School of Business',
    distance: '0.3 mi',
    category: 'career',
    isFree: true,
    organizer: 'Stern Career Center',
  },
  {
    id: 'nyu-4',
    title: 'Tisch Film Screening',
    startTime: '9:00 PM',
    endTime: '11:00 PM',
    venue: 'Tisch School of the Arts',
    distance: '0.4 mi',
    category: 'arts',
    isFree: false,
    organizer: 'Tisch Film Society',
  },
]

export const NYU_DEMO_MARKERS = [
  {
    id: 'nyu-1',
    longitude: -73.9972,
    latitude: 40.7295,
    title: 'Bobst Library Event',
    category: 'academic',
    type: 'school' as const,
  },
  {
    id: 'nyu-2',
    longitude: -73.9980,
    latitude: 40.7300,
    title: 'Kimmel Game Night',
    category: 'social',
    type: 'club' as const,
  },
  {
    id: 'nyu-3',
    longitude: -73.9960,
    latitude: 40.7290,
    title: 'Stern Workshop',
    category: 'career',
    type: 'school' as const,
  },
  {
    id: 'nyu-4',
    longitude: -73.9985,
    latitude: 40.7285,
    title: 'Tisch Screening',
    category: 'arts',
    type: 'club' as const,
  },
]

